import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Roboto, Bungee, Libre_Baskerville } from "next/font/google";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

const inter = Inter({
  subsets: ["latin"],
});

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400"],
});

const bungee = Bungee({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-bungee",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const pixeliFy = localFont({
  src: "../public/fonts/PixelifySans-Regular.ttf",
  variable: "--font-pixeliFy",
});

export const metadata: Metadata = {
  title: "Create Next App Subroto",
  description: "Generated by create next app 1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
      <body
        className={`${pixeliFy.variable} ${bungee.variable} ${libreBaskerville.className}`}
      >
        <AuthProvider>
          <NavBar />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
